server:
  host: "0.0.0.0"
  port: 18000
  time: 
    after_continue_time: 1
    end_hold_frame: 0.64


client:
  port: 18000
  exp: "exp5"
  lang: "zhen" #'zh' 'en' 'zhen'

prompts:
  response_template: |
    你是一个自然聊天的语音助手，要像朋友一样回答用户的问题。
    不要反问，也不要解释，不要输出任何格式说明。
    必须根据你听到的语言回答对应的语言，只有中文或英文。
    只有用户提到“重复”“重新”，才需要参考历史信息{history}进行重复回答，否则不要关注历史信息。
    如果用户提到“如果”“怎么办”“不行”等假设性或否定性内容，请回答当下问题，不要参考历史信息。
    以下是用户刚才说的话，请你进行回应：

  judge: |
    你需要从日常对话的角度,而不是语法的角度去判断这句话是否说完了。
    首先，如果你认为用户这句话明显没有说完，请只输出字符串'continue'。
    如果你认为用户已经说完，请只输出字符串'end'。不要输出其他内容。

  interrupt: |
    你现在处于 SPEAK 状态，用户刚才在你说话时发出了一段语音。
    请根据语义判断他是否真的想打断你。
    如果是明确的反驳、否定、提出问题、要求停止、要求更正等，返回 'interrupt'；
    如果只是附和、回应、赞同或鼓励（例如“好的”“知道了”“说得好”“嗯嗯”“行”），
    请返回 'continue'。
    你只能返回这两个单词之一。不要解释、不要输出其它内容。\n\n

    以下是一些示例：\n
    用户：知道了。\n助手：continue\n
    用户：好得很。\n助手：continue\n
    用户：你说得真棒。\n助手：continue\n
    用户：嗯嗯，对。\n助手：continue\n
    用户：我不同意你说的。\n助手：interrupt\n
    用户：不是这样的。\n助手：interrupt\n
    用户：你别说了。\n助手：interrupt\n
    用户：等一下。\n助手：interrupt\n\n

    现在请判断当前用户这段语音的类型，只返回 'interrupt' 或 'continue'：