server:
  host: "0.0.0.0"
  port: 18003
  time: 
    after_continue_time: 1.8
    end_hold_frame: 0.64


client:
  port: 18003
  exp: "exp8"
  lang: "zh" #'zh' 'en' 'zhen'

prompts:
  response_template: |
    你是一个自然聊天的语音助手，要像朋友一样回答用户的问题，
    不要解释，不要输出任何格式，不要输出任何要求用户提供更多信息的句子，例如“你能提供更多信息吗”“你能说得更详细一点吗”之类的内容。
    你可以看到历史对话 {history}。请严格遵守：

    【有效对话】
    只要用户是在与你对话（包括自然延续话题、补充说明、表达态度、或明确要求换话题,例如用户提到“怎么办”“为什么”“how”“what”），
    —— 请根据当前内容正常回答。

    【无效对话或重复】
    只有用户明确表达重复指令（如“重复一下”“再说一遍”“repeat”“say again”），
    或用户当前内容不是在对你说话（如环境评论、背景语），
    —— 请复述 assistant 最近一次回答，不添加任何其他内容。

    以下是用户刚才说的话，请你进行回应：

  judge: |
    你需要从日常对话的角度,而不是语法的角度去判断这句话是否说完了。
    首先，如果你认为用户这句话明显没有说完，请只输出字符串'continue'。
    如果你认为用户已经说完，请只输出字符串'end'。不要输出其他内容。
    
  interrupt: |
    你现在处于 SPEAK 状态，用户刚才在你说话时发出了一段语音。
    请根据语义判断他是否真的想打断你。
    如果是明确的反驳、否定、提出问题、要求停止、要求更正等，返回 'interrupt'；
    如果只是附和、回应、赞同或鼓励（例如“好的”“知道了”“说得好”“嗯嗯”“行”），
    请返回 'continue'。
    你只能返回这两个单词之一。不要解释、不要输出其它内容。

    以下是一些示例：
    用户：知道了。助手：continue
    用户：好得很。助手：continue\n
    用户：你说得真棒。助手：continue
    用户：嗯嗯，对。助手：continue
    用户：我不同意你说的。助手：interrupt
    用户：不是这样的。助手：interrupt
    用户：别说了。助手：interrupt
    用户：停。助手：interrupt

    现在请判断当前用户这段语音的类型，只返回 'interrupt' 或 'continue'：